debug: True
postgres:
  debug: False
  database: aiocomments_test
  user: aiocomments_user
  password: aiocomments
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

filestorage:
  root: ../files

redis:
  host: 127.0.0.1
  port: 6379

host: 127.0.0.1
port: 8086

apps:
  ['aiocomments']

middlewares: [
  # json_response_middleware should be the last one
  'core.middlewares.json_response_middleware',
]